---
# tasks file for naturalis.base

- name: Install base packages
  apt:
    name: "{{ base_packages }}"
    update_cache: yes
    cache_valid_time: 3600

- name: Allow 'adm' to passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%adm'
    line: '%adm ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Create user
  user:
    name: "{{ item.username }}"
    group: adm
    shell: /bin/zsh
  loop: "{{ admin_users }}"
  loop_control:
    label: "{{ item.username }}"
  tags: admin_users

- name: Set ssh_dir
  file:
    state: directory
    name: /home/{{ item.username }}/.ssh
    owner: "{{ item.username }}"
    group: adm
    mode: 0700
  loop: "{{ admin_users }}"
  loop_control:
    label: "{{ item.username }}"
  tags: admin_users


- name: Set public key
  copy:
    content: "{{ item.key_format | default ('ssh-rsa') }} {{ item.public_key }} {{ item.username }}"
    dest: /home/{{ item.username }}/.ssh/authorized_keys
    owner: "{{ item.username }}"
    group: adm
    mode: 0600
  loop: "{{ admin_users }}"
  loop_control:
    label: "{{ item.username }}"
  tags: admin_users





